### ISSUE TITLE
Output state as string instead of class when serializing model

### ISSUE THREAD

**Issue by bjrnblm** [spatie/laravel-model-states#10]
I am trying to combine this package with `Spatie\Activitylog` and `LogsActivity` trait.

```
<?php namespace App\Models;

use App\States\ArticleState;
use App\States\Concept;
use App\States\Published;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\ModelStates\HasStates;

class Article extends Model
{
    use HasStates, LogsActivity;

    protected $fillable = ['title', 'state'];
    protected static $logFillable = true;

    protected function registerStates(): void
    {
        $this
            ->addState('state', ArticleState::class)
            ->allowTransitions([
                [Concept::class, Published::class],
            ]);
    }
}
```

In the `activity_log.properties` column it tries to insert the state, but since its `Concept::class` it gets translated to `{}`:
```
{
  "attributes": {
    "state": {},
    "title": "My title"
  }
}
```

The same thing happens when you want to output the model to json:

```
$article = Article::find(1);
return $article->toJson();
```

```
{
  "id":1,
  "title":"My title",
  "state":{}
}
```

is it possible to translate `state` automatically to a string when serializing a model with `HasStates`?

**Comment by brendt** [comment]
I'm not sure yet, but will definitely look into this!

**Comment by brendt** [comment]
Turned out it was pretty easy, just had to implement `JsonSerializable` on the abstract `State` class. Added in 1.1.2: https://github.com/spatie/laravel-model-states/releases/tag/1.1.2

**Comment by bjrnblm** [comment]
Wow, that was quick! Thanks 👍
