### ISSUE TITLE
 Tinyint columns are not loading state correctly

### ISSUE THREAD

**Issue by rodrigo-spb** [spatie/laravel-model-states#12]
Tinyint columns are not loading state correctly.

when the model is loaded Laravel brings 'null' instead of the instance of State.:

**Comment by brendt** [comment]
Can you PR a failing test for this?

**Comment by brendt** [comment]
Thanks for the help. It's fixed in 1.1.3: https://github.com/spatie/laravel-model-states/releases/tag/1.1.3
