### ISSUE TITLE
infinite loop on model saved event with transition

### ISSUE THREAD

**Issue by mediaimprove** [spatie/laravel-model-states#125]
Hello, i've this method in a subscriber which currently causes an infinite loop (because of a $model->save() on inserting data and the following state transition):

```
    public function saved(OrderAddressSavedEvent $event): void
    {
        $orderAddress = $event->orderAddress;

        if (! $this->validateOrderAddressAction->execute($orderAddress)) {
            $orderAddress->transitionTo(OrderAddressNotValidated::class);

            return;
        }

        $orderAddress->transitionTo(OrderAddressValidated::class);
    }
```

Thinking about if a method $model->transitionToWithoutEvents is a PR worth, or is there a much more simpler solution?

**Comment by brendt** [comment]
We're working on a v2 which uses eloquent casts instead of events, so this problem will be fixed. v2 will be tagged when Laravel 8 arrives.
