### ISSUE TITLE
Unable to use getStates or getStatesFor

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-model-states#133]
When using a configuration like:
```
        $this->addState('state', LineTaskState::class)
            ->default(Open::class)
            ->allowTransition(Open::class, InProgress::class, ToInProgress::class)
            ->allowTransition(Open::class, Resolved::class, ToResolved::class)
            ->allowTransition(InProgress::class, Resolved::class, ToResolved::class);
```

Then calling on the model with the registered states either getStates or getStatesFor, I end up with the following respectively:
```
>>> LineTask::getStates()
=> Illuminate\Support\Collection {#5228
     all: [
       "state" => Illuminate\Support\Collection {#5229
         all: [],
       },
     ],
   }
>>> LineTask::getStatesFor('state')
=> Illuminate\Support\Collection {#5225
     all: [],
   }
```

Is there something I'm missing or is this really working at all?

**Comment by brendt** [comment]
Feel free to submit a tested PR with a fix, or a test that fails so I can fix it. I won't be investing more time in v1, since we're close to tagging v2.

**Comment by RobertCordes** [comment]
This is still an issue on 2.1.0, even with a fresh Laravel install. 😕 @ragingdave Have you managed to fix this?
