### ISSUE TITLE
Allow all transitions for a given state?

### ISSUE THREAD

**Issue by ghostal** [spatie/laravel-model-states#135]
Is there a way to say "any and all transitions for this state property are okay"?

As far as I can tell, the answer is no - if the transition key doesn't exist in the `allowedTransitions` property of `StateConfig` for a state, then an exception is thrown.

I have in mind something like this:

```php
$this
    ->addState('role', Role::class)
    ->allowAllTransitions()
    ->default(User::class);
```

And then maybe the ability to still selectively specify transition classes for specific transitions:

```php
$this
    ->addState('role', Role::class)
    ->allowAllTransitions()
    ->allowTransition(User::class, Administrator::class, Transition\UserToAdministrator::class)
    ->default(User::class);
```

Looking at the code for `resolveTransition()`, it seems as though setting a new boolean property on `StateConfig` to true with the proposed `allowAllTransitions()` method could prevent the method returning early, and so allow the `DefaultTransition` class to be returned in all cases.

If the above seems inappropriate, does this question mean I might be "Doing It Wrong"? :thinking:

**Comment by brendt** [comment]
That's indeed not possible. You can bypass the allowed state checks by directly performing them using the `transition` method: 

```
$payment->state->transition(new CreatedToFailed($payment, 'error message'));
```

More info here: https://spatie.be/docs/laravel-model-states/v1/working-with-transitions/02-custom-transition-classes
