### ISSUE TITLE
Conditional state registration

### ISSUE THREAD

**Issue by enver1323** [spatie/laravel-model-states#136]
Dear Developers,

Hello, I have encountered an issue, when I have different scenarios for the same state, which depends on other fields of my model. Let's say, I have a state field "stage", which stores current stage of my model "Document" and the model has two possible types, so called "direction"s, which are "inbox" and "outbox". What I did was conditionally registering states in "registerStates" method, so now it look like this:

`protected function registerStates(): void
    {
        if ($this->isInbox()) {
            $this->addState('stage', DocumentInboxStage::class)->default(DocumentInboxDraft::class);
            return;
        }
        $this->addState('stage', DocumentOutboxStage::class)->default(DocumentOutboxDraft::class);
    }`

So my check on the `$this->isInbox()` fails, since it is simply checking the "direction" field being equal to some constant value.

`public function isInbox(): bool
    {
        return $this->direction == self::DIRECTION_INBOX;
    }`

I would be truly grateful for any glimpse of the advice. Thank you in advance!

**Comment by brendt** [comment]
That kind of functionality isn't supported, and also not possible to support given. I'd say the cleaner solution is to have two model classes both using the same database table, each model can specify its own state configuration.

**Comment by enver1323** [comment]
Thank you for a nice suggestion. I've followed it and divided into two classes with global scopes
