### ISSUE TITLE
Class App\States\Order\StatusState does not extend the `Spatie\ModelStates\State` base class.

### ISSUE THREAD

**Issue by CodyPChristian** [spatie/laravel-model-states#138]
Hey, having an issue while trying to set up this package.

Not quite sure where I went wrong as I was following the docs exactly.

```
Spatie\ModelStates\Exceptions\ClassDoesNotExtendBaseClass
Class App\States\Order\StatusState does not extend the `Spatie\ModelStates\State` base class.
```

model
```php
<?php

namespace App\Models;

use Eloquent;
use SoftDeletes;
use Carbon\Carbon;
use Spatie\ModelStates\HasStates;
use App\States\Order\StatusState;
use App\States\Order\GetFees;
use App\States\Order\Draft;

class Order extends Eloquent
{
    use SoftDeletes, HasStates;
    protected $dates = ['deleted_at', 'order_date'];
    protected $table = 'orders';
    protected $hidden = ['deleted_at'];
    
    protected function registerStates(): void
    {
        $this
            ->addState('status', StatusState::class)
            ->allowTransition(GetFees::class, Draft::class)
            ->default(GetFees::class);
    }
```

StatusState in App/States/Order/
```php
<?php

use Spatie\ModelStates\State;

abstract class StatusState extends State
{
    abstract public function status(): string;
}
```

Draft
```php
<?php

use App\States\Order\StatusState;

class Draft extends StatusState
{
    public static $name = 'Draft';

    public function status(): string
    {
        return 'Draft';
    }
}
```

GetFees
```php
<?php

use App\States\Order\StatusState;

class GetFees extends StatusState
{
    public static $name = 'Get_Fees';

    public function status(): string
    {
        return 'Get_Fees';
    }
}
```

**Comment by CodyPChristian** [comment]
Also to add this is using package version 1.9 and latest Laravel 7 version on PHP 7.4.

**Comment by brendt** [comment]
Could you reproduce the error and debug why it was thrown? Either using the exception trace or by clicking around with your IDE.

**Comment by msnegurski** [comment]
Hey, @CodyPChristian , I think the issue is that you did not namespace your classes.

**Comment by anthonytp** [comment]
I have been seeing this error sporadically on our live site running on Vapor. Annoyingly, it goes away when I build and deploy the code again without changing anything, so I've not been able to find the cause.

I saw the error again today, the message was:

> Class App\\States\\Invoice\\InvoiceBaseState does not extend the `Spatie\\ModelStates\\State` base class.

@CodyPChristian our class has a namespace declaration but still caused this error.

```
<?php

namespace App\States\Invoice;

use Spatie\ModelStates\State;

abstract class InvoiceBaseState extends State
{
    public static array $states = [
        Draft::class,
        Issued::class,
    ];
}
```

**Comment by brendt** [comment]
Could this have to do with how states are auto discovered? We're going to scan the filesystem to do so. This happens in `State::resolveStateMapping()`, maybe you could debug over there?

**Comment by anthonytp** [comment]
I had a look at the `State::resolveStateMapping()` method and the first thing it checks for is the static array `$states`
```
    private static function resolveStateMapping(): array
    {
        if (isset(static::$states)) {
            return static::$states;
        }
        ...
```
My class has that array defined so it should immediately return from this method.

**Comment by brendt** [comment]
Does the same problem happen when the mapping is not provided?

**Comment by CodyPChristian** [comment]
Yes I have tried with the namespace and had the same issue before I gave up and used a different package. Currently I am not using this package because I could never get it to work after spending a few days on it.
