### ISSUE TITLE
Visibility of $field and $model properties of State

### ISSUE THREAD

**Issue by lorenzolosa** [spatie/laravel-model-states#146]
In version 2 of laravel-model-states a State knows to which field is attached, which is great. However, the $field property is private, and there is no way to access it, which limits it usefulness. In particular:
* states cannot use this information;
* custom transition classes need to know the name of the field, and therefore it is not possible to use the same transition with different field names (either in the same model or in different ones).

Moreover, from v1 to v2 also the $model property of State was changed from protected to private, which creates a similar issue: the state behavior cannot depend on the model. I had some code that accessed the $model, which does not work with v2. I could also move all the logic to the model, of course, but that would reduce the usefulness of the states.

In my code I am now using workarounds for both these issues, so it's not terrible for me, but changing those properties from private to protected would be a better solution. Are there any negative consequences in doing that?

Additionally, while thinking about this, I came up with a related idea. My proposal would be to change the handle() method of Transition to handle(Model $model, string $field). The benefit would be:
* moves $model from the constructor to handle(), therefore simplifying the constructor and making possible to instantiate the transition even without knowledge of the model.
* providing information about the $field (which is currently missing).

(Hopefully) the change would be backward-compatible. Transitions written in the current way should still work: their handle() method would receive two additional arguments, that would be just ignored.

If this change in the handle() method is considered potentially useful, I can try to implement it, see if everything works and prepare a pull request. This is a distinct proposal from $field and $model protected, which looks useful anyway to me, but I'm writing them all in the same issue because they are related.

**Comment by asantibanez** [comment]
Hello @brendt ! Great package! Just came across and started using it.

Stumbled on this same thing yesterday/today @lorenzolosa. Have also applied some workarounds to get the changed `field` but it would be nice that this property was public or at least have a getter to facilitate post processing.

Right now, I added a getter to the abstract State class in order to get the changed field. Works, but would be best if this was given by the transition itself.

![image](https://user-images.githubusercontent.com/5126648/101267188-20963f80-3724-11eb-9288-a6a364b56e88.png)

**Comment by brendt** [comment]
How about we add two getters? `getModel` and `getField`?

Changing how `handle` works on transitions wouldn't be possible without another breaking change, and we deliberately want to keep them in line with how Laravel jobs work (context data in the constructor, DI in handle).

**Comment by brendt** [comment]
FYI `getModel` and `getField` are added in 2.0.2: https://github.com/spatie/laravel-model-states/releases/tag/2.0.2

**Comment by brendt** [comment]
Feel free to discuss this issue further, but I'm going to close it since I believe the original issue is now solved.
