### ISSUE TITLE
Change Field name for states

### ISSUE THREAD

**Issue by Algeneralo** [spatie/laravel-model-states#148]
Currently, we have state management with this library, and all things are good.
The only issue that we will face is that we want to change the field name after its returns to the model:
EX:
I have a `conversation` model, which has a column called `status_id` since the library use the same filed name to represent the state, so I have to use it `$conversation->status_id->transtionTo(....)`, but I want to change it to be `$conversation->status->transtionTo(....)`

Is there any idea that helps with that?

**Comment by brendt** [comment]
There's no support for this. I'd recommend calling the field `status` instead.
