### ISSUE TITLE
Attribute not cast correctly if default is set

### ISSUE THREAD

**Issue by gjm** [spatie/laravel-model-states#157]
If the model has a default value set in `$attributes` for the state attribute, the value is not properly set after hydrating the model and the default is always used.

```php
class MyModel extends Model
{
    use HasStates;

    protected $attributes = [
        'status' => 'valid',
    ];

    protected $casts = [
        'status' => Status::class,
    ];
}
```

If I do `MyModel::first()` the value of `status` is always `valid` no matter what the value in the database is.

**Comment by ju5t** [comment]
We have the exact same issue. I haven't been able to look into this much further, but in our case it happens on a list of items within a Livewire component. Removing the default fixes it for us.

**Comment by pszucs** [comment]
I've had the same issue with the spatie/laravel-enum package. Instead of setting the default value in the `$attributes` property, I use the model's construct:

```php
public function __construct(array $attributes = [])
{
     $this->attributes['state'] = DraftState::$name;

     parent::__construct($attributes);
}
```

This works, but being able to set it in the `$attributes` would be nice.

**Comment by brendt** [comment]
Could you debug what exactly goes wrong? Since we're using Laravel's built-in casts, I'd assume should look for the problem within Laravel…

**Comment by pszucs** [comment]
I dug further into this issue but was unable to find out where things go wrong. I'm able to solve the issue by [configuring the default state](https://spatie.be/docs/laravel-model-states/v2/working-with-states/01-configuring-states) on the state class.

My previous comment about transitions now seems to be a separate problem, I'll open another issue for that one.

**Comment by brendt** [comment]
Ok, thanks! Closing this one then.
