### ISSUE TITLE
How do I make state transitions mandatory on all model operations? 

### ISSUE THREAD

**Issue by adrienne** [spatie/laravel-model-states#174]
Maybe I'm missing something, but I want to *enforce* a transition happening any time the `status` field on a model record is changed, no matter where that happens. (Including third-party CRUD stuff that i can't easily change to use    
 `->transitionTo`, because we're doing some stuff with Backpack, which is the whole problem here). 

I tried adding an observer to the `saving` event like this:
```
if ($model->isDirty('status')) {
    $newStatus = $model->status;
    $model->status = $model->getOriginal('status');
    $model->status->transitionTo($newStatus);
} 
```
but that ends up with a max execution time error and no logged PHP errors -- I assume it's looping for some reason. 

The goal, again, is that anytime someone sets or changes the status on a model, the appropriate Transition runs automatically.

Is there really no way to do this?

**Comment by brendt** [comment]
I'm not sure if that's possible. The only way I can think of is to treat state fields as "read only". By manually implementing the mutator for those fields and prohibiting changing them from outside the model? 

We've relied on trust within our team to never change state fields manually.
