### ISSUE TITLE
[Question] History of states

### ISSUE THREAD

**Issue by eduarguz** [spatie/laravel-model-states#18]
I have been looking for this package and this one [spatie/laravel-model-status](https://github.com/spatie/laravel-model-status)

First, I thought these were the same but now I see they are different. I really like the safety and well structured form this package handles "states" but I also like the way that laravel-model-status has a history...

The Question is... 
Could we have a history using this package? 
Would it be possible to mix these packages? 
Would you be interested in some sort of history, meaning this is a secondary table and the model state would be read from this database?

Thanks for making these packages available for us!!

**Comment by bjrnblm** [comment]
@eduarguz I have no experience with combining that specific package.

However I do use [spatie/laravel-activitylog](https://github.com/spatie/laravel-activitylog) in combination with `laravel-model-states` and it is working fine so far.

1. `laravel-model-states` is making sure only the correct states in the correct order are being used
2. `laravel-activitylog` is keeping a history of states and other fields

**Comment by brendt** [comment]
We discussed this, and decided we don't want this package to be concerned with keeping state history. Our suggestion would be the same as @bjrnblm to use laravel-activitylog

**Comment by sawirricardo** [comment]
Hi @brendt , really love this package (and the blog post you've written about this state pattern). I think it would be nice if you include about this discussion, especially your suggestion to use laravel-activitylog to save the state changes in the docs. I believe some of the people who use this package, may have the same thought with @eduarguz. Again, really appreciate for your team's works.


> We discussed this, and decided we don't want this package to be concerned with keeping state history. Our suggestion would be the same as @bjrnblm to use laravel-activitylog
