### ISSUE TITLE
Add `StateChanged` event

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-model-states#2]
After a transition is run.

**Comment by VictorAvelar** [comment]
Would please be a bit more verbose on the acceptance criteria of the task, so that I can check if I can jump in please.

**Comment by brendt** [comment]
Sure: after a transition is run, we want an event to be triggered so that users can hook into it. This needs to happen:

- Add a `StateChanged` event containing the old and new state, the transition, as well as the model it was performed on. 
- This event should be triggered after performing the transition, this is where this needs to happen: https://github.com/spatie/laravel-model-states/blob/master/src/State.php#L227. You'll have to store the result in a variable, then trigger the even and then return the result.
- You should also add a test to ensure the event was triggered
- You should add a new page in the docs (https://github.com/spatie/laravel-model-states/tree/master/docs/working-with-transitions) called "transition events" which for now simply lists this one event.

**Comment by VictorAvelar** [comment]
I will work on it, and push when its "reviewable" thanks for the quick response.

**Comment by brendt** [comment]
Awesome, thanks!

**Comment by VictorAvelar** [comment]
So I prototyped an implementation on #7 awaiting for review. 🚀

**Comment by VictorAvelar** [comment]
Hi @brendt I think you can close this one right? or am I missing something?

**Comment by freekmurze** [comment]
Yup.
