### ISSUE TITLE
Testing if a transition is allowed

### ISSUE THREAD

**Issue by tobz-nz** [spatie/laravel-model-states#28]
I would find it really useful if there was a `canTransitionTo($state)` method on the base State class.

This would allow certain UI controls(or values in a control) to show depending on the current state, for example.

**Comment by tobz-nz** [comment]
For example the base `State` could implement something like:

```php
    /**
     * Test if this State can transition to the given State
     *
     * @param string|\Spatie\ModelStates\State $state
     * @return boolean
     */
    public function canTransitionTo($state): bool
    {
        $state = State::make($state, $this->model);

        try {
            $this->model->resolveTransitionClass(
                static::resolveStateClass(static::class),
                static::resolveStateClass($state)
            );
        } catch (CouldNotPerformTransition $e) {
            return false;
        }

        return true;
    }
```

... I don't think this is testing for specific fields though, so would probably need more work.

Might work better as a similar method in the `HasStates` trait instead.

**Comment by tobz-nz** [comment]
... Actually. moving most of the logic in `transitionTo()` to `canTransitionTo()` then `transitionTo` uses the new method and simply does the actual transition if the check passes would be a much better solution.

**Comment by brendt** [comment]
It's a great feature, though I'm planning to make some changes to how state fields are mapped to their state classes. I'd like to get that one finished first, before looking at this one: https://github.com/spatie/laravel-model-states/pull/31

**Comment by brendt** [comment]
I added it in the v2 branch

**Comment by travisobregon** [comment]
Hi @brendt,

I had a look at your implementation of `canTransitionTo` on the v2 branch. Do you think this method should also call `canTransition` on the Transition class to filter out some states? Something like this maybe?:

```php
$states = collect($model->state->transitionableStates());

$allowedTransitions = $states->map(function ($state) use ($model) {
	return $model->resolveTransitionClass(
		static::resolveStateClass($model->state),
		static::resolveStateClass(new $state($model))
  	);
})->filter(function ($transition) use ($request) {
        // This is needed because custom Transition classes are stored as a string in `allowedTransitions` in StateConfig.
  	if (is_string($transition)) {
	  	$transition = new $transition($request);
	}
  
  	return $transition->canTransition();
});
```

**Comment by brendt** [comment]
This is already built-into the transitionableStates method on the StateConfig class though? https://github.com/spatie/laravel-model-states/blob/master/src/StateConfig.php#L83

**Comment by travisobregon** [comment]
It looks like `canTransition` is only called when you attempt to apply a transition. 

My use case is that if there are 2 possible states to transition to, I would like to use `canTransition` to determine which state should be transitioned to based on the model's data. Does that make sense? 

Maybe there is a better way to achieve what I am trying to do.

**Comment by brendt** [comment]
Maybe you should give a concrete example?

**Comment by travisobregon** [comment]
Sorry for being unclear. Let me know if this makes sense.

#### Model:

```php
class Payment extends Model
{
    use HasStates;

    protected $guarded = [];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->state = $this->state ?? new Created($this);
    }

    protected function registerStates(): void
    {
        $this->addState('state', PaymentState::class)
            ->allowTransition(Created::class, Failed::class, ToFailed::class)
            ->allowTransition(Created::class, Paid::class);
    }
}
```

#### Custom Transition:

```php
class ToFailed extends Transition
{
    /** @var \Spatie\ModelStates\Tests\Dummy\Payment */
    private $payment;

    /** @var string */
    private $message;

    public function __construct(Payment $payment, string $message)
    {
        $this->payment = $payment;
        $this->message = $message;
    }

    public function canTransition(): bool
    {
        return false;
    }

    public function handle()
    {
        //
    }
}
```

Using a fresh payment in the Created state, `$payment->state->transitionableStates()` will return an array containing Failed and Paid. I was thinking that it should only return Paid because the ToFailed transition's implementation of `canTransition` returns `false`.

**Comment by brendt** [comment]
Ah right, got it! Thanks for the clarification and sorry for the delay. It's a valid issue, though I'm not entirely sure if we can add it. Transitions could allow for custom constructor arguments (as with `$message` in your example), and we have no way of passing these when calling `$payment->state->transitionableStates()` 🤔

**Comment by booni3** [comment]
@travisobregon did you ever find a workaround to this? It's such a shame that we need to duplicate the logic to check if the state can be transitioned to, outside of the transition class.

My use case for this currently is on the front end (show/hide buttons based on this logic). The `transitionableStates` method is perfect apart from this point.

**Comment by booni3** [comment]
I am using the below on my model and it seems to do the trick so far. The only issue I can see is if the can method relies on other parameters entered into the transition class constructor or if the params in the constructor are not optional, it will fail...

```php
public function canTransitionTo(string $toClass, $field = 'state'): bool
{
    try {
        $transition = $this->resolveTransitionClass(get_class($this->{$field}), $toClass);
        if (method_exists(app($transition), 'canTransition')) {
            return app()
                ->makeWith($transition, ['orderReturn' => $this])
                ->canTransition();
        }
    } catch (TransitionNotFound $e) {
        // do nothing
    }

    $states = $this->state->transitionableStates($field);

    return in_array($toClass, $states);
}
```

On the front end, we can then do something like this...

```blade
@if($model->canTransitionTo(Approved::class))
   <button>Approve</button>
@endif
```

obviously, if you are not using transition classes then none of this is needed and we can just check the transitional states array.

@brendt, not sure if you had any other thoughts on this?
