### ISSUE TITLE
Add Ignition solutions for state exceptions

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-model-states#3]

**Comment by mateusjunges** [comment]
Hi @brendt, i'm trying to solve this issue for you. Can you help me explaining about the solutions for state exceptions?

**Comment by travisobregon** [comment]
Would it be best to make the methods in the Exception classes their own class? If the ProvidesSolution interface is used, the solution for the exceptions won't be as detailed/specific? I suppose you could have multiple conditions in the `getSolution` method to figure out which solution to return?

Or would you want to create a SolutionProvider? In the case of the InvalidConfig exception, I think there would be 5 solutions, which may be confusing to cycle through?

**Comment by brendt** [comment]
I'm ok with adding separate exception classes, as long as they extend the `InvalidConfig` exception.

**Comment by travisobregon** [comment]
I'm not sure how to go about this? Is this what you have in mind? :

```php
class InvalidConfig extends Exception
{
    public static function unknownState(string $field, Model $model): InvalidConfig
    {
        $modelClass = get_class($model);

        return new UnknownState("No state field found for {$modelClass}::{$field}, did you forget to provide a mapping in {$modelClass}::registerStates()?");
    }

    //
}

class UnknownState extends InvalidConfig implements ProvidesSolution 
{
    public function getSolution(): Solution
    {
        //
    }
}
```

With this, both `throw UnknownState::unknownState();` and `throw InvalidConfig::unknownState();` work. Is that okay?

**Comment by brendt** [comment]
Yes! My main concern is that we want to keep backwards compatibility, if we'd make all new classes which don't extend `InvalidConfig`, we must tag a new major release. Your approach is good!

**Comment by brendt** [comment]
Released as https://github.com/spatie/laravel-model-states/releases/tag/1.4.0

Thanks @travisobregon
