### ISSUE TITLE
States are sometimes not initialised?

### ISSUE THREAD

**Issue by tobz-nz** [spatie/laravel-model-states#30]
I'm having an issue using a State in an accessor where the State is the string value, not the State instance. Here's my current workaround:

```php
use App\ModelStates\Status;

...

public function getStatusBadgeClassAttribute()
    {
        if (is_string($this->status)) {
            // seems sometimes the state trait doesn't boot properly sometimes?
            // kick it in manually
            $this->status = Status::make($this->status, $this);
        }

        return sprintf('badge-%s', $this->status->type());
    }
```

This seems to only be required sometimes. I've not worked out why.

**Comment by brendt** [comment]
Can you submit a PR with a failing test? I'll take a look at it.

**Comment by tobz-nz** [comment]
I'll try make some time to wip one up 👍

**Comment by tobz-nz** [comment]
This issue seems be when calling `$model->refresh()` - the statuses are not initialized.

```php
dump($model->status) // App\ModelStates\Incomplete
dump($model->refresh()->status) // "Incomplete"
```


Sorry, I still haven't had time to setup an full isolated working example.
