### ISSUE TITLE
Add toArray method to State

### ISSUE THREAD

**Issue by tobz-nz** [spatie/laravel-model-states#38]
Adding a 1toArray()` method would make it possible to output the object in a json response for example.

Should return an array of all public properties by default?

**Comment by brendt** [comment]
Can you specify a little more how you'd implement this? It seems to me that, because of state-specific methods, you'll always have to implement `toArray` on the concrete state base classes anyway, so I see little value in adding it to `State`.

Feel free to tell me otherwise though ;)

**Comment by tobz-nz** [comment]
Couldn't you return an array of all public properties by default? 
Similar to how event classes broadcast public props for example.

something like:

```php
...

function toArray() 
{
    return (new ReflectionClass($this))
       ->getProperties(ReflectionProperty::IS_PUBLIC));
}
```

**Comment by brendt** [comment]
You could, but when would you use this package in such a way? The purpose is to define abstract state classes which define methods for concrete states to implement. I'm not sure when you'd define public properties on a state class?

**Comment by tobz-nz** [comment]
hmm, yeah I see your point. I think you're right, probably best for users to implement `toArray()` on the concrete as required.

**Comment by brendt** [comment]
Ok, I'll close this one for now.
