### ISSUE TITLE
Override transitions for testing

### ISSUE THREAD

**Issue by peterfox** [spatie/laravel-model-states#44]
I'm currently using the model states package. I'm finding it difficult to write tests with it though. Is there any way to override what the initial state on a model is or even changing the state without saving to the database? Namely say I have state A, B and C. The model can only go from A to B and B to C. I want to create a model instance without saving it to the database. When I make the model and transition from A to B it executes the eloquent query.

At current if I want to make an instance of my model in a non default state I have to do something like:
```php
$myModel = new MyModel();
$myModel->setRawAttributes([
    'state' => new SomeState($myModel);
]);
```

It feels a bit clumsy doing it this way though.e I was wondering what other's thoughts on this might be?

Not sure if this is a related issue but also, where I'm setting the State as a class string in a factory.

```php
$factory->state(App\MyModel::class, 'something', function ($faker) {
    return [
        'state' => \App\States\SomethingState::class
    ];
});
```

When I try to check the state, I seem to be getting a `Call to a member function is() on string` which is confusing things further.

**Comment by brendt** [comment]
How about

```php
$myModel = new MyModel([
    'state' => SomeState::class,
]);
```

Take a look at the tests in this package: https://github.com/spatie/laravel-model-states/blob/master/tests/StateTest.php
