### ISSUE TITLE
use unsigned integer field instead of string

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-model-states#46]
Is it possible to use an unsigned integer field instead of a string? I would prefer use ints with foreign keys to a lookup table instead of a string in my database.

I have tried setting this up as per the instructions but am getting the following error:

> "Object of class App\Domain\Opportunities\States\Open could not be converted to int"

Below is an example of my Open state

```
<?php

namespace App\Domain\Opportunities\States;

class Open extends OpportunityState
{
    public static $name = 1;

    public function label(): string
    {
        return 'Open';
    }

}

```

my OpportunityState class

```
<?php

namespace App\Domain\Opportunities\States;

use Spatie\ModelStates\State;

abstract class OpportunityState extends State
{

    abstract public function label(): string;
}
```

and my registerStates function in my Opportunity

```
    protected function registerStates(): void
    {
        $this->addState('opportunity_stage_id', OpportunityState::class)
            ->default(Open::class);
    }
```

**Comment by brendt** [comment]
I'll look into this!

**Comment by brendt** [comment]
We actually already support integer fields, so I'm not quite sure where your error comes from. Please have a look at the test for integer states, and also compare the related migrations to yours: https://github.com/spatie/laravel-model-states/blob/master/tests/StateTest.php#L264-L279

Maybe you could share the whole stack trace, or submit a PR with a test that fails, showing the issue?

**Comment by ashgibson** [comment]
Yep, my bad. It all works! Thanks!
