### ISSUE TITLE
Undefined variable: modelClass

### ISSUE THREAD

**Issue by lorlab** [spatie/laravel-model-states#47]
Hi! I get this 500 ErrorException instead of the expected TransitionNotFound  when trying to make a transition that hasn't been registered: 

`Undefined variable: modelClass in TransitionNotFound.php line 52`

Shouldn't it be `$this->modelClass?`

**Comment by brendt** [comment]
Feel free to submit a PR with a test and a fix, if you're unable to I'll take a look at this next week

**Comment by brendt** [comment]
Fixed with 1.4.2: https://github.com/spatie/laravel-model-states/releases/tag/1.4.2
