### ISSUE TITLE
Error on default transition with non-standard status field name

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-model-states#49]
Getting an error when using a non-standard state field (status_id) and using the default transition class:

Argument 2 passed to Spatie\ModelStates\Events\StateChanged::__construct() must be an instance of Spatie\ModelStates\State or null, string given, called in ......

If I look at where the error is coming from - Spatie\ModelStates\State.php (233)

`event(new StateChanged($this, $mutatedModel->state, $transition, $this->model));`

The error is coming from the reference to `$mutatedModel->state`. Should ->state be referenced like this or should it be resolving to the custom field name?

**Comment by brendt** [comment]
It's a bug, but one that we unfortunately cannot properly fix right now: the state class doesn't know about which field it's linked to… I'll make changes to the event, though we'll need to properly fix it in v2.

**Comment by brendt** [comment]
Temporary fix released as 1.5.0: https://github.com/spatie/laravel-model-states/releases/tag/1.5.0

**Comment by brendt** [comment]
Will be fixed in v2!

**Comment by rela589n** [comment]
Wait a bit! Why we can't just locate state field in $model::$stateFields?
