### ISSUE TITLE
Search on docs not working

### ISSUE THREAD

**Issue by robjbrain** [spatie/laravel-model-states#52]
It seems like the search isn't working for the docs for this package. I had a look at the requests in the console and Algolia was returning 0 hits for every term (transition, payment, state, serialize etc) so I imagine it's something wrong with your Algolia account indexing the text.

Just an FYI 👍

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. I've notified Algolia and hopefully they will index the documentation soon.

**Comment by Ganganation** [comment]
Still or maybe again this is not working.
