### ISSUE TITLE
Getting transitionableStates() as objects rather than strings

### ISSUE THREAD

**Issue by robjbrain** [spatie/laravel-model-states#55]
It seems strange to me that transitionableStates() returns a string instead of the State object.

It means you cannot do something like this:

```
<div class="dropdown">
    State
    <ul class="dropdown-items">
        @foreach($model->state->transitionableStates() as $state)
            <li class="{{ $state->color() }}">{{ $state->name }}</li>
        @endforeach
    </ul>
</div>
```

You'll get an error `Call to a member function color() on string` this is because `transitionalStates()` returns the string morph class name (or full class name) rather than the object.

It does not seem like there is a way to easily get a list of states as objects.

I attempted a quick hack to retrieve the objects but ran into more problems trying to resolve the actual State class.

This fails because it always return the morph name e.g. "approved" and then the error "Class 'approved' not found".

```
<?php

namespace App\Traits;

use Spatie\ModelStates\HasStates;

/**
 * @mixin \App\Models\BaseModel
 */
trait HasStatesTrait
{
    use HasStates;

    /**
     * @param string $fieldName
     * @return array
     */
    public function transitionableStateObjects(string $fieldName): array
    {
        return array_map(function($stateClass) {
            return new $stateClass($this);
        }, $this->$fieldName->transitionableStates());
    }
}

```

I've attempted to resolve the state class (there does not appear to be any documentation on resolving the state class) but so far with no luck.

I've tried

```
// Assuming "status" is the field name
$className = $this->status->resolveStateClass($stateClass);
```

I've also tried 
```
// use Spatie\ModelStates\State
Status::resolveStateClass($stateClass)
```

Although I can't see how that would work at all since the Status class won't know about the object.

It seems obvious to me that there should be a method available to retrieve a State class and thus be able to access to the `color()` method and yet it does not seem obviously available. I would happily attempt to contribute this feature if need be but at the moment i'm unsure if it is in fact possible and simply not documented very well, or whether it is impossible and a feature request.

For completeness here's my complete code, maybe i've missed something really obvious?

```
namespace App\Domain\Links\Models;

use Spatie\ModelStates\HasStates;

class Link extends BaseModel
{
    use HasStates;

    /**
     * @var string
     */
    public $table = 'links';

    /**
     * @throws \Spatie\ModelStates\Exceptions\InvalidConfig
     */
    protected function registerStates(): void
    {
        $this
            ->addState('status', StatusState::class)
            ->allowTransition([Pending::class, Rejected::class], Approved::class)
            ->allowTransition([Pending::class, Approved::class], Rejected::class)
            ->default(Pending::class);
    }
}

namespace App\Domain\Links\States;

use Spatie\ModelStates\State;

abstract class StatusState extends State
{
    abstract public function color(): string;
}

namespace App\Domain\Links\States;

class Approved extends StatusState
{
    /**
     * @var string
     */
    public static string $name = 'approved';

    public function color(): string
    {
        return 'success';
    }
}

namespace App\Domain\Links\States;

use App\Icons\Icon;

class Pending extends StatusState
{
    /**
     * @var string
     */
    public static string $name = 'pending';

    /**
     * @return string
     */
    public function color(): string
    {
        return 'warning';
    }
}

App\Domain\Links\States;

class Rejected extends StatusState
{
    /**
     * @var string
     */
    public static string $name = 'rejected';

    public function color(): string
    {
        return 'danger';
    }
}

```

**Comment by brendt** [comment]
We cannot initialise state objects because they need a concrete model to be constructed. You can use `Status::make($stateClass, $model)`.
