### ISSUE TITLE
Make default transition class configurable

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-model-states#56]
A configurable default transition class would allow developers to add project-specific behaviour to the default transition class. Stuff like writing log entries, timestamps etc.

We could even go as far as to allow a default transition class per model.

**Comment by brendt** [comment]
One question that needs answering: do we want to provide a config file, or simple a method in the `HasStates` trait: `defaultTransitionClass`. Each model could override it. This seems like a simpler solution than adding a config file. 

What do you think @freekmurze ?

**Comment by A-Lawrence** [comment]
As a package user, I'd _much_ rather it be model specific and therefore part of the trait.  Not because it's less effort, but because it offers the most flexibility in handling the default transitions for specific models.

**Comment by brendt** [comment]
Agree, let's do it in the trait!

**Comment by brendt** [comment]
Closing this one since there doesn't seem to be much interest in it.
