### ISSUE TITLE
Allow relationship on status field at the same time

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-model-states#59]
Referencing a previous issue - #46 

I found out it wasn't working because i had an eloquent relationship referencing the state field e.g.

```
protected function registerStates(): void
{
   $this->addState('status_id', StatusState::class);
}
```
and
```
public function status()
{
   return $this->belongsTo(Status::class, 'status_id');
}
```

When the HasStates traits does its magic, it converts the status field into a state object and then eloquent is unable to eager load the relationship.

Is there any way to get this to work or are the 2 features mutually exclusive?

The reason why I am trying to achieve this is because I would prefer to make use of a lookup table for user friendly labels etc on the different states rather than within code. I may be a bit old school, but I prefer to have FK checks rather than string values that aren't enforced at the database level.

I can also see a use case to allow other things to be defined in the database such as allowing users to toggle the mustBePaid boolean in the stitcher.io reference article rather than have this hardcoded.

**Comment by brendt** [comment]
Hmm, it's a valid use case but I'm not sure how we could support these both 🤔if you can come up with any ideas you're free to discuss them, but I won't be actively looking into solutions for it, sorry.

**Comment by Pugzy** [comment]
@ashgibson were you able to find an appropriate way to implement the above? 

It appears that what you are trying to achieve is similar to my own scenario and I have had no luck hacking about as of yet. I'm wanting to keep a record or who triggered the state changes and also provide a database lookup for state information like yourself. 

I was rather relieved when I found this issue as it aligned with my goals and and ran into the same hurdles I had fallen at.

My only current work around is to use a separate database attribute and keep it in line with the states identifier which doesn't seem ideal.

**Comment by agoalofalife** [comment]
@Pugzy @ashgibson 
At the moment I use 1.9 version, in any case..
I found some decision for me and want to share it
We can override static property `$name`. Obviously, another table which has keys(list statuses), e.g status_id can change constantly.
I suggest dynamically set ids in state classes for property `$name`;
Have a look, the example adapt for you:
```php
  protected function registerStates(): void
    { 
       // it's just example, i use another way but the concept should be clear
        $map = [
            New::class => Status::where('name', 'new')->get()->first()->id,
            Handled::class   => Status::where('name', 'handled')->get()->first()->id,
        ];

        $this
            ->addState('status_id', StatusState::class)
            ->default(New::class)
            ->allowTransitions([
                [
                    New::class, Handled::class,
                ],
            ]);

        foreach (self::getStates()['status_id'] as $stateClass) {
            $stateClass::$name = $map[$stateClass];
        }
    }
 ```
this way is still working for me, maybe it will be useful for  you

**Comment by agoalofalife** [comment]
@Pugzy @ashgibson I am back with answer.
It's difficult, we have a lot of states in model.
I see only one chance solve this problem.

We have create two models:
- this one for read
- and this another one for write
In model for write, we will describe logic from this package.
I agree, it doesn't perfect, but what do you have options?
