### ISSUE TITLE
Question on transitioning to the default state

### ISSUE THREAD

**Issue by travisobregon** [spatie/laravel-model-states#79]
I understand that custom transitions are useful for side effects, but is it possible to have a custom transition just for the Received state in the example below or something similar? Or would you suggest listening for the `StateChanged` event in this situation and do some checks there?

```
class Order extends Model
{
    // …

    protected function registerStates(): void
    {
        $this
            ->addState('state', OrderState::class)
            ->default(Received::class);
    }
}
```

**Comment by brendt** [comment]
You want a custom transition class when setting the default state — did I understand that correct?

**Comment by travisobregon** [comment]
Yes, that's correct. 

I am just doing this right now:

```
public static function booted()
{
    static::created(function ($model) {
        // Send emails, log activity, etc.
    });
}
```

But it feels like it would be more intuitive to do these side effects in a custom transition, which is where I would put the side effects for other states that are not default. Does that make sense?

**Comment by brendt** [comment]
I think a `defaultTransition` would be a valid feature. Feel free to submit a PR. If you're not up for that I'll do my best to look into this soon.

**Comment by travisobregon** [comment]
Would PR #57 conflict with this feature?

Not sure if the initialisation of the `HasStates` trait would cause an issue because it sets the default state too? Would it be okay to assume that if a `defaultTransitionClass` was provided, do not initialise the field?  Something like:

```
    public function initializeHasStates(): void
    {
        foreach (self::getStateConfig() as $stateConfig) {
            if (! $stateConfig->defaultStateClass) {
                continue;
            }

            if ($stateConfig->defaultTransitionClass) {
                continue;
            }

            $this->{$stateConfig->field} = new $stateConfig->defaultStateClass($this);
        }
    }
```

And then after https://github.com/spatie/laravel-model-states/blob/master/src/HasStates.php#L32, do this?

```
if ($transition = $stateConfig->defaultTransitionClass) {
    app()->call([new $transition($model), 'handle']);
}
```

**Comment by brendt** [comment]
That PR seems to be inactive. I think my personal preference is towards specifying default states on a per model level, as I suggested in https://github.com/spatie/laravel-model-states/pull/57#issuecomment-574052067

Feel free to submit a new PR in favour of the old one.
