### ISSUE TITLE
Expected behavior when transitioning to the same state

### ISSUE THREAD

**Issue by mehrancodes** [spatie/laravel-model-states#81]
This is what I'm getting when someone trying to transition from Pending twice.

```
Transition from `Pending` to `Pending` on model `Course` was not found, did you forget to register it in `Course::registerStates()`?
```

Isn't this the business of transitions to take care of which states are allowed to get transitioned and which not?

had to manually throw an exception if the current state is pending...

here are my registered states btw
```
    protected function registerStates(): void
    {
        $this->addState('status', CourseState::class)
            ->allowTransition(Draft::class, Pending::class, DraftToPending::class)
            ->allowTransition(Pending::class, Approved::class)
            ->allowTransition(Approved::class, Published::class)
            ->default(Draft::class);
    }
```

**Comment by brendt** [comment]
If you want to allow transitions to the same state, you should explicitly register them.

**Comment by mehrancodes** [comment]
Well, I don't want to allow that, but seems like I should also check manually if the current state is Pending, I should not do the transition again.
