### ISSUE TITLE
PHPUNIT: Call to a member function transitionTo() on string

### ISSUE THREAD

**Issue by mehrancodes** [spatie/laravel-model-states#82]
I'm custom $name properties for my states and while all my state classes and abstract class are in the same namespace, I'll get this error when I'm trying to run the transitioning via my automated test.
The issue is that it can't serialize the Model state and returns back the value stored in the DB.
But the strange thing is that this error doesn't occur when I test it manually via a browser!

So here's one of my states:
```
<?php

namespace MyPackage\Courses\App\States\Course;

class Draft extends CourseState
{
    public static $name = 'draft';

    public function type(): string
    {
        return 'draft';
    }
}
```

and also my phpunit.xml
```
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="TELESCOPE_ENABLED" value="false"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <server name="BCRYPT_ROUNDS" value="4"/>
        <server name="CACHE_DRIVER" value="array"/>
        <server name="MAIL_DRIVER" value="array"/>
        <server name="QUEUE_CONNECTION" value="sync"/>
        <server name="SESSION_DRIVER" value="array"/>
    </php>
```

**Comment by mehrancodes** [comment]
Seems like the problem comes from [State.php:322](https://github.com/spatie/laravel-model-states/blob/81e02be303e34d1ccf6b039d274ba8aadbf04971/src/State.php#L322)

`is_subclass_of` Can't recognize its child classes when we use `static::class`

**Comment by mehrancodes** [comment]
Never mind! it was because I've been using `Event::fake()` during the test!

But now I would like to see how can I test it when I want to mock my event?

**Comment by brendt** [comment]
> But now I would like to see how can I test it when I'm mocking my event?

This package relies on model events to work. You can mock only specific events and don't fake the model events.
