### ISSUE TITLE
'whereState()' and 'whereNotState()' is not working

### ISSUE THREAD

**Issue by floreean** [spatie/laravel-model-states#84]
If i put them as in the examples. i always get zero results:

`$payments = Payment::whereState('state', Paid::class);`

Is this not supported anymore?

**Comment by brendt** [comment]
There's a dedicate test class for this, and it seems to still work. Please refer to the documentation or take a look at how the tests work: https://github.com/spatie/laravel-model-states/blob/master/tests/ScopeTest.php
