### ISSUE TITLE
This package doesn't work with Laravel Nova Badge field

### ISSUE THREAD

**Issue by phuclh** [spatie/laravel-model-states#87]
I have a Nova Badge field like this:

```
Badge::make('State')->map([
                'down' => 'danger',
                'up'   => 'success',
            ]),
```

It always returns the error:
```
exception: "ErrorException"
file: "/Users/phucle/Code/larseo-saas/nova/src/Fields/Badge.php"
line: 148
message: "Undefined variable: mappedValue"
```

It seems when I access the `state` attribute via `$this->state`. It returns the class state instead of string.

Updated: My quick fix is using `resolveUsing`. Something like that:
```
Badge::make('State')
                ->resolveUsing(function ($state) {
                    return $state::$name;
                })->map([
                    DownState::$name => 'danger',
                    UpState::$name   => 'success',
                ]),
```

But I would like to know the elegant fix for that 👯

**Comment by freekmurze** [comment]
We don't use this package in combination with Nova, so we're not going to invest time in this issue. If there is any easy fix, please PR it 🙂
