### ISSUE TITLE
Cast not applied in model event handlers...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-model-states#88]
First, let me say that I'm not sure that the problem is with this package, Laravel, or me.

Anyway, the problem is related to a state variable being cast to the state object when used within one of a model's `created|updated|deleted|etc` events.

It **seems** that within the event, the state attribute is **only** a string...and not a state object.

I've only tried the `updating` and `updated` events and I've tried them via a model observer class as well as via a closure in the model's `booted` method a la:
```php
protected static function booted()
{
    static::updated(function ($myModel) {
        // ...
    });
}
```

So, using the `booted` method, here's what seems to happen:
```php
protected static function booted()
{
    static::updated(function ($myModel) {
        dump($myModel->state_attribute); // outputs *string*, eg `enabled`, `disabled`, etc...

        $sameModel = self::find($myModel->id); // re-fetch *same* model...

        dump($sameModel->state_attribute); // outputs *state object*...
    });
}
```

So...not sure where the problem is or if this is by design in this package or Laravel.  It's obviously not an insurmountable problem, but it is annoying.  And, if it's an error somewhere, it is a bit of a time sink since I've spent a little time trying to figure out why my code wasn't working as expected.

**Any thoughts/advice...?**

(Edit: Corrected variable name used in last `dump()` in example...from `$myModel` -> `$sameModel`.)

**Comment by mvdnbrk** [comment]
I came up with this issue earlier.
Opened a PR to solve this issue See #36 

Unfortunately the PR was closed automatically due to inactivity.

**Comment by telkins** [comment]
> I came up with this issue earlier.
> Opened a PR to solve this issue See #36
> 
> Unfortunately the PR was closed automatically due to inactivity.

@mvdnbrk Thx for the post.  Sorry to everyone, but I didn't actually search other issues/PRs to see if anyone had brought this up yet/before.  I **normally** do a quick search, but didn't this time around.

It would appear that this is a package issue after all and not a framework issue.  How can this be?  Seems odd to me, but. I guess I don't know how the Laravel casting works under the hood.

Could it be better/simpler to require developers to explicitly use Laravel 7's Custom Eloquent Casts....for those using 7+...?

**Comment by mvdnbrk** [comment]
@telkins As I mentioned I have already submitted a PR solve the issue.

@brendt probably just forgot to take a look at it and merge it in, as a consequence the PR got closed automatically.

As far as I know @brendt planned a V2 of this package which will take advantage of the custom eloquent casting introduced by the Laravel framework in v7.

**Comment by brendt** [comment]
Yeah I'm working on a v2 which makes everything much more easy. But I'm happy to merge your PR in v1, I indeed lost track of that one.

**Comment by brendt** [comment]
Tagged as 1.6.2: https://github.com/spatie/laravel-model-states/releases/tag/1.6.2
