### ISSUE TITLE
does not work with yajra DataTables library

### ISSUE THREAD

**Issue by SamDeimos** [spatie/laravel-model-states#90]
I am using the [Yajra Datatable](https://github.com/yajra/laravel-datatables) library with Eloquent Bulder to create the columns, when configuring the model-states library it does not show anything in the table, the php CLI is cleared and it is time to restart the services, at the moment I am on a local server WampServer

```
    public function query()
    {
        return Holidays::with('employees.persons')->select();
    }
```

**Comment by brendt** [comment]
We don't support that package, you'll need to debug this in your code. If there are simple changes that need to be done in order to support it, I'm open for a PR.
