### ISSUE TITLE
Allow conditionals to be added to transitions

### ISSUE THREAD

**Issue by kurucu** [spatie/laravel-model-states#91]
If I understand the following function properly then it will raise an exception, because it's for validating manual transitions.

    public function canTransition(): bool

But, what would be handy, is a similar function that helps to determine transitionable states by adding conditions to them.

Take an example - A DocumentState is Reviewing. While a valid transition (ReviewingToIssued) exists, it should only be transitionable when all reviewers have signed off on the document contents.

**Comment by brendt** [comment]
Feel free to submit a PR detailing this idea.
