### ISSUE TITLE
My PHPUnit test fails

### ISSUE THREAD

**Issue by Kryptonien** [spatie/laravel-model-states#93]
https://github.com/spatie/laravel-model-states/blob/1e2626bd5d492f8e1bc7533f64f4e55f4b781182/src/HasStates.php#L204

Hello, for some reason this line makes my PHPUnit test fails, when I remove it everything works as intended.

More explanation:

Consider this model User.php:

```PHP
namespace App\Models;

use App\Models\States\UserState\Active;
use App\Models\States\UserState\Archived;
use App\Models\States\UserState\UserState;
use Spatie\ModelStates\HasStates;

class User
{

    use HasStates;

    protected function registerStates(): void
    {
        $this->addState('state', UserState::class)
            ->allowTransitions([
                [Active::class, Archived::class],
                [Archived::class, Active::class]
            ])
            ->default(Active::class);
    }
}
```

With this controller UserController.php:

```PHP
namespace App\Http\Controllers;

use App\Models\User;

class UserController extends Controller
{

    public function edit(User $user)
    {
        dd($user->state);
    }
}
```

And finally this UserControllerTest.php snippet
```PHP
namespace Tests\Feature\Controllers;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserControllerTest extends TestCase
{

    use RefreshDatabase;

    /** @test * */
    public function my_test_case()
    {
        $user = factory(User::class)->create();
        $uri = route('user.edit', $user->id);

        $response = $this->login()->get($uri);
    }

    private function login()
    {
        $user = factory(User::class)->create();

        return $this->actingAs($user);
    }
}

```

When accessing through the URI (E.g. http://localhost/en/user/1/edit), `$user->state` (from dd() function in the Controller) returns the intended `App\Models\States\UserState\Active` class. But when accessing through PHPUnit `$user->state` returns the "unformatted" value from the DB unless I remove `static::$stateFields = []; `

Any idea ? Am I doing something wrong ?

**Comment by brendt** [comment]
Are you faking the event bus in your tests? This package uses model events under the hood.

**Comment by Kryptonien** [comment]
No I'm not mocking the Event. The method getStateConfig is called before any event. It's when the model is initialized. Since getStateConfig has a weird behaviour on my end, no event gets triggered at all because it consider the Model is not configured.

**Comment by brendt** [comment]
What's the error, or which assertion fails?

**Comment by Kryptonien** [comment]
Here's the Exception's string:
`Call to a member function transitionableStates() on string`


Let's take my previous example:
```PHP
    public function edit(User $user)
    {
        dd($user->state);
    }
```

It should return a class, but I got a string instead. Only happens when doing Tests. It might have to do with factory. Not sure why though.

**Comment by Kryptonien** [comment]
After further testing. Here's a much easier way to reproduce the issue.

```
namespace Tests\Feature\Controllers;

use App\Models\User;
use App\Models\States\UserState\Active;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserControllerTest extends TestCase
{

    use RefreshDatabase;

    /** @test * */
    public function newly_created_user_should_cast_state_column_to_correct_class()
    {
        $user = factory(User::class)->create();

        $this->assertEquals($user->state, Active::class);
    }

}
```

With the above code, the assertion fails because "state" is still a string when it shouldn't.

If you need further informations, let me know.

**Comment by MacTwister** [comment]
Yeah, I also have the same issue as @Kryptonien with L8 in my tests. I ended up adding `User::boot()` in each test which uses the state package.

I also noticed if any test in a testcase had an HTTP test (eg. using `$this->get('/users/')`, I would no longer get the above state field as a string error in other tests in that file.

**Comment by Kryptonien** [comment]
Thx for the tip @MacTwister, I no longer have the issue with this workaround.

**Comment by brendt** [comment]
These problems will be gone with v2, which doesn't rely on the model event system anymore, but requires Laravel ^8. It'll be tagged soon

**Comment by simonbowen** [comment]
I am also facing this issue, I have updated to the latest version of the package (2.0.0). I know this was only released today but v2 doesn't seem to address the issue stated here.
