### ISSUE TITLE
Error when using getStatesFor('state')

### ISSUE THREAD

**Issue by ClementN** [spatie/laravel-model-states#97]
Error
==========
```
Call to a member function color() on string
```

Scenario 
============
(keeping the same example as the documentation)

**InvoiceController.php** 

```
..........................
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoicesStates = Invoice::getStatesFor('state');

        return view('models.invoices.index', compact('invoicesStates'));
    }
..........................
```

**views/models/invoices/index.blade.php** 

```
..........................
<!-- My Invoices -->
<div>
   @foreach($invoices as $invoice)
      Invoice color:  {{ $invoice->state->color() }}
   @endforeach
</div>
..........................
```

**Context:** 
Laravel 7
laravel-model-states: 1.6.3

Is this a bug? Any suggestion to fix?

**Comment by mtakahashi1977** [comment]
its String.

**Comment by brendt** [comment]
A few issues:

- Where does `$invoices` come from in your blade file? There's only the `$invoicesStates` variable passed to the view in the controller
- The error has to do with the state field not being properly populated. It uses Eloquent events to do this. I'm not sure why exactly it happens, but I'm working on a v2 which gets rid of this problem. It's not done yet though.

**Comment by brendt** [comment]
v2 is tagged now
