### ISSUE TITLE
Suggestion - Add transition validation

### ISSUE THREAD

**Issue by davidpiesse** [spatie/laravel-model-states#98]
Add Laravel style validation to transitions.
This will prevent a transition running if it does not pass the validation conditions.

Just before the handle method is called / first thing it does is ``` validate()``` which uses the private props of the transition class and an array of rules (set in function)
```php  
public function rules(): array {} 
``` 

Why?
It may be that you want to go from state Pending to Paid when a user pays for a order.
Validation can check that the paid_at datetime field is null, the incoming data about a user is valid user has a cc on file.

```php
public function rules(): array 
{
    return [
       'order.paid_at' => 'empty',
       'user.has_cc' => 'accepted',
    ];
}
```
I can see this is something I will need on many future projects- so I am happy to code it up if you think is suitable for this package. :)

**Comment by brendt** [comment]
I don't see much added value here: there's no autocompletion on the strings returned from the `rules` array. Why not do these checks directly in the `canTransition` method where you have access to the type hinted objects directly.

**Comment by davidpiesse** [comment]
True - it leaves something to be desired in the implementation.
The canTransition was my original thought and looking back at it implementing inside canTransition would be better.. 

Thanks for the input.
